version: '3'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=your-db-user
      - DB_PASSWORD=your-db-password
      - DB_NAME=your-db-name
      - DB_HOST=your-db-host
      - DB_PORT=your-db-port
      - JWT_SECRET=your-secret
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your-db-user
      POSTGRES_PASSWORD: your-db-password
      POSTGRES_DB: your-db-name
    ports:
      - "5432:5432"
